# ~/~ begin <<README.md#hugo.toml>>[init]
baseURL = 'https://ana.help'
languageCode = 'en-us'
title = 'Ana Meisel'
theme = 'hugo-PaperMod'
description = 'ã‹¡'
[markup.goldmark.renderer]
unsafe = true
# ~/~ end